enum ZHotKey {
    Z_ANCHOR_MASK         = 0x000000FF,
    Z_FULL_SCREEN         = 0x00000100,
    Z_NEXT_SCREEN         = 0x00000200,
    Z_MOVE                = 0x00010000,
    Z_RESIZE              = 0x00020000,
	Z_MOVE_NEXT_SCREEN    = Z_MOVE | Z_NEXT_SCREEN,
	Z_MOVE_TOP_LEFT       = Z_MOVE | Z_TOP_LEFT,
	Z_MOVE_TOP            = Z_MOVE | Z_TOP,
	Z_MOVE_TOP_RIGHT      = Z_MOVE | Z_TOP_RIGHT,
	Z_MOVE_LEFT           = Z_MOVE | Z_LEFT,
	Z_MOVE_CENTER         = Z_MOVE | Z_CENTER,
	Z_MOVE_RIGHT          = Z_MOVE | Z_RIGHT,
	Z_MOVE_BOTTOM_LEFT    = Z_MOVE | Z_BOTTOM_LEFT,
	Z_MOVE_BOTTOM         = Z_MOVE | Z_BOTTOM,
	Z_MOVE_BOTTOM_RIGHT   = Z_MOVE | Z_BOTTOM_RIGHT,
	Z_RESIZE_NEXT_SCREEN  = Z_RESIZE | Z_NEXT_SCREEN,
	Z_RESIZE_TOP_LEFT     = Z_RESIZE | Z_TOP_LEFT,
	Z_RESIZE_TOP          = Z_RESIZE | Z_TOP,
	Z_RESIZE_TOP_RIGHT    = Z_RESIZE | Z_TOP_RIGHT,
	Z_RESIZE_LEFT         = Z_RESIZE | Z_LEFT,
	Z_RESIZE_CENTER       = Z_RESIZE | Z_CENTER,
	Z_RESIZE_RIGHT        = Z_RESIZE | Z_RIGHT,
	Z_RESIZE_BOTTOM_LEFT  = Z_RESIZE | Z_BOTTOM_LEFT,
	Z_RESIZE_BOTTOM       = Z_RESIZE | Z_BOTTOM,
	Z_RESIZE_BOTTOM_RIGHT = Z_RESIZE | Z_BOTTOM_RIGHT,
	Z_RESIZE_FULL_SCREEN  = Z_RESIZE | Z_FULL_SCREEN
};
typedef UInt32 ZHotKey;


void ZHandleHotKey(ZHotKey hotKey);
CGSize ZGetRatio(ZHotKey hotKey);


@interface ZAgent : NSObject {
	NSStatusItem *statusItem;
}

@end
